[programs.localnet]
truesight_protocol = "4338bCaJ8TjcNGmqhQs1FPHZsq2k4PQw15sgNXaEgogw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
